<?php
session_start();
require_once '../../db/db.php';
require_once '../../config/config.php';

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}


$userId = $_SESSION['user_id'];

// Handle PDF Download
if (isset($_GET['download']) && $_GET['download'] == 'pdf') {
    require_once('../../lib/TCPDF/TCPDF/tcpdf.php'); // Make sure to include TCPDF library
    
    /// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('Your Company Name');
$pdf->SetAuthor('Your Company Name');
$pdf->SetTitle('Orders Report');

// Remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Set margins
$pdf->SetMargins(15, 15, 15);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 15);

// Add a page
$pdf->AddPage();

// Set font for title
$pdf->SetFont('helvetica', 'B', 20);

// Company Logo and Header
$pdf->Image('../../assets/img/logo2.jpg', 15, 15, 33); // Adjust path and dimensions
$pdf->Cell(0, 0, '', 0, 1); // Space for logo

// Title
$pdf->SetTextColor(52, 58, 64); // Dark gray
$pdf->Cell(0, 10, 'Orders Report', 0, 1, 'C');

// Add date
$pdf->SetFont('helvetica', '', 10);
$pdf->SetTextColor(108, 117, 125); // Secondary gray
$pdf->Cell(0, 5, 'Generated on: ' . date('F d, Y'), 0, 1, 'C');

// Add line break
$pdf->Ln(10);

// Initialize styles for the table
$style = array(
    'border' => 0,
    'vpadding' => '8',
    'hpadding' => '8',
    'fgcolor' => array(33, 37, 41),
    'bgcolor' => false,
    'font-size' => 10,
    'font-style' => ''
);

// Create the table header style
$headerStyle = array(
    'border' => 0,
    'vpadding' => '8',
    'hpadding' => '8',
    'fgcolor' => array(255, 255, 255),
    'bgcolor' => array(78, 115, 223), // Primary blue
    'font-size' => 11,
    'font-style' => 'B'
);

// Generate HTML for the orders table
$html = '
<table cellpadding="5" style="border-collapse: collapse; width: 100%;">
    <thead>
        <tr style="background-color: #4e73df; color: white;">
            <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e3e6f0;">Order ID</th>
            <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e3e6f0;">Order Date</th>
            <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e3e6f0;">Status</th>
            <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e3e6f0;">Items</th>
            <th style="padding: 12px; text-align: right; border-bottom: 2px solid #e3e6f0;">Total Amount</th>
        </tr>
    </thead>
    <tbody>';
    
   // Fetch orders from database
   $ordersQuery = $conn->prepare("
   SELECT 
       o.id,
       o.total_amount,
       o.status,
       o.created_at,
       COUNT(oi.id) as item_count,
       GROUP_CONCAT(
           CONCAT(p.name, ' (', oi.quantity, ')')
           SEPARATOR ', '
       ) as items_summary
   FROM 
       orders o
   LEFT JOIN 
       order_items oi ON o.id = oi.order_id
   LEFT JOIN 
       products p ON oi.product_id = p.id
   WHERE 
       o.user_id = ?
   GROUP BY 
       o.id, o.total_amount, o.status, o.created_at
   ORDER BY 
       o.created_at DESC
");
$ordersQuery->bind_param("i", $userId);
$ordersQuery->execute();
$ordersResult = $ordersQuery->get_result();
$orders = $ordersResult->fetch_all(MYSQLI_ASSOC);

foreach ($orders as $order) {
   $html .= '<tr>
               <td>' . htmlspecialchars($order['id']) . '</td>
               <td>' . date('F d, Y', strtotime($order['created_at'])) . '</td>
               <td>' . htmlspecialchars($order['status']) . '</td>
               <td>' . htmlspecialchars($order['items_summary']) . '</td>
               <td>RM ' . number_format($order['total_amount'], 2) . '</td>
             </tr>';
}

$html .= '</tbody></table>';


// Add footer with border
$html .= '
<div style="margin-bottom: 30px; border-top: 2px solid #e3e6f0; padding-top: 20px; text-align: center;">
    <p style="color: #858796; font-size: 10px; margin: 5px;">This is an automatically generated report. For questions, please contact support.</p>
    <p style="color: #858796; font-size: 10px; margin: 5px;">Generated by AutiReach ©' . date('Y') . '</p>
</div>';



// Output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('orders_report.pdf', 'D');
exit();
}

// Include navigation based on user role
if (isset($_SESSION['role'])) {
    if ($_SESSION['role'] == 'community') {
        include '../../includes/cnav.php';
    } elseif ($_SESSION['role'] == 'member') {
        include '../../includes/mnav.php';
    }
}


try {
    // Get all orders with their items (same query as before)
    $ordersQuery = $conn->prepare("
        SELECT 
            o.id,
            o.total_amount,
            o.status,
            o.created_at,
            o.tracking_number,
            o.order_status,
            DATE_ADD(o.created_at, INTERVAL 7 DAY) AS estimated_delivery_date,
            COUNT(oi.id) as item_count,
            GROUP_CONCAT(
                CONCAT(p.name, ' (', oi.quantity, ')')
                SEPARATOR ', '
            ) as items_summary
        FROM 
            orders o
        LEFT JOIN 
            order_items oi ON o.id = oi.order_id
        LEFT JOIN 
            products p ON oi.product_id = p.id
        WHERE 
            o.user_id = ?
        GROUP BY 
            o.id, o.total_amount, o.status, o.created_at, o.tracking_number, o.order_status
        ORDER BY 
            o.created_at DESC
    ");
    $ordersQuery->bind_param("i", $userId);
    $ordersQuery->execute();
    $ordersResult = $ordersQuery->get_result();
    $orders = $ordersResult->fetch_all(MYSQLI_ASSOC);

    // Generate tracking number if not present
    foreach ($orders as &$order) {
        if (empty($order['tracking_number'])) {
            $trackingNumber = strtoupper(bin2hex(random_bytes(4))); // Generate random tracking number
            $updateQuery = $conn->prepare("UPDATE orders SET tracking_number = ? WHERE id = ?");
            $updateQuery->bind_param("si", $trackingNumber, $order['id']);
            $updateQuery->execute();
            $order['tracking_number'] = $trackingNumber;
        }
    }

} catch (Exception $e) {
    error_log($e->getMessage());
    header('Location: orders.php?error=An error occurred while fetching orders');
    exit;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Orders</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/boxicons@2.0.7/css/boxicons.min.css" rel="stylesheet">
    <style>
        :root {
            --primary-color: #4e73df;
            --secondary-color: #858796;
        }
        
        body {
            background-color:rgb(145, 173, 255);
            color: #5a5c69;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        
        .card {
            border: none;
            box-shadow: 0 0.15rem 1.75rem 0 rgba(58, 59, 69, 0.15);
            border-radius: 0.35rem;
        }
        
        .card-header {
            background-color: #f8f9fc;
            border-bottom: 1px solid #e3e6f0;
            padding: 1.5rem;
        }
        
        .page-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 2rem;
        }
        
        .btn-download {
            background-color: var(--primary-color);
            color: white;
            border: none;
            padding: 0.5rem 1rem;
            border-radius: 0.35rem;
            transition: all 0.2s;
        }
        
        .btn-download:hover {
            background-color: #2e59d9;
            color: white;
        }
        
        .table {
            margin-bottom: 0;
        }
        
        .table th {
            background-color: #f8f9fc;
            color: #4e73df;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.8rem;
            letter-spacing: 0.1em;
        }
        
        .table td {
            vertical-align: middle;
        }
        
        .status-badge {
            padding: 0.25em 0.75em;
            border-radius: 50rem;
            font-size: 0.85em;
            font-weight: 600;
        }
        
        .status-pending {
            background-color: #ffeeba;
            color: #856404;
        }
        
        .status-completed {
            background-color: #c3e6cb;
            color: #155724;
        }
        
        .status-processing {
            background-color: #b8daff;
            color: #004085;
        }
        
        .order-summary {
            max-width: 300px;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
        
        @media (max-width: 768px) {
            .table-responsive {
                border: 0;
            }
            
            .card-body {
                padding: 0;
            }
        }
    </style>
</head>
<body>
    <div class="container py-5">
        <div class="card">
            <div class="card-header">
                <div class="page-header">
                    <h2 class="m-0">My Orders</h2>
                    <?php if (!empty($orders)): ?>
                        <a href="?download=pdf" class="btn btn-download">
                            <i class='bx bx-download me-2'></i>Download Recipt
                        </a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="card-body">
                <?php if (isset($_GET['error'])): ?>
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <?= htmlspecialchars($_GET['error']) ?>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                <?php endif; ?>
                
                <?php if (empty($orders)): ?>
                    <div class="alert alert-info m-3">
                        <i class='bx bx-info-circle me-2'></i>You have no orders yet.
                    </div>
                <?php else: ?>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Order ID</th>
                                    <th>Order Date</th>
                                    <th>Status</th>
                                    <th>Items</th>
                                    <th>Total Amount</th>
                                    <th>Tracking Number</th>
                                    <th>Est. Delivery</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($orders as $order): ?>
                                    <tr>
                                        <td>#<?= htmlspecialchars($order['id']) ?></td>
                                        <td><?= date('F d, Y', strtotime($order['created_at'])) ?></td>
                                        <td>
                                            <span class="status-badge status-<?= strtolower($order['status']) ?>">
                                                <?= htmlspecialchars($order['status']) ?>
                                            </span>
                                        </td>
                                        <td class="order-summary" title="<?= htmlspecialchars($order['items_summary']) ?>">
                                            <?= htmlspecialchars($order['items_summary']) ?>
                                        </td>
                                        <td>RM <?= number_format($order['total_amount'], 2) ?></td>
                                        <td> JNT<?= htmlspecialchars($order['tracking_number'] ?? 'N/A') ?></td>
                                        <td><?= date('F d, Y', strtotime($order['estimated_delivery_date'])) ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>